bot:
  name: GYM
  token: 1837289890:AAFUDMG45GXGN2u5MqYkb1kpKeHqMEqXTrM

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_bot
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

